import json
import math
import os

import pytest

import qa_gcode

DSF_SAMPLES = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", "DuetSoftwareFramework",
                                            "src", "UnitTests", "File", "GCodes"))


@pytest.mark.parametrize("comment,current,expected", [
    ("LAYER_CHANGE", 4, 5),              # PrusaSlicer/OrcaSlicer/SuperSlicer: +1
    ("LAYER:0", 0, 1),                   # Cura counts from 0
    ("LAYER:12", 3, 13),
    (" layer 7, Z = 1.400", 0, 7),        # Simplify3D counts from 1
    ("LAYER_COUNT:418", 0, 0),           # "LAYER" followed by "_": no layer
    ("Layer height: 0.1", 0, 0),         # case-sensitive: not forwarded as a layer
    ("BEFORE_LAYER_CHANGE", 2, 2),       # PrusaSlicer custom marker: does not start with a known string
    (" --- layer 3", 0, 0),              # KiriMoto: DSF does not forward it
    ("TYPE:WALL-OUTER", 2, 2),
])
def test_layer_comment(comment, current, expected):
    assert qa_gcode.layer_comment(comment, current)[0] == expected


def test_object_comments():
    assert qa_gcode.layer_comment("MESH:cube.stl", 1)[1] == ("start", "cube.stl")
    assert qa_gcode.layer_comment("MESH:NONMESH", 1)[1] == ("stop", None)
    assert qa_gcode.layer_comment("printing object cube_id_0_copy_0", 1)[1] == ("start", "cube_id_0_copy_0")
    assert qa_gcode.layer_comment("stop printing object cube_id_0_copy_0", 1)[1] == ("stop", None)


PRUSA_LIKE = """; generated by PrusaSlicer
M83
G90
G1 Z0.2 F600
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
M486 S0 A"cube"
;TYPE:External perimeter
G1 X10 Y10 F6000
G1 X20 Y10 E1.0 F1200
G1 X20 Y20 E1.0
M486 S-1
G1 E-0.8 F2400
G1 X30 Y30 F9000
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z0.4
M486 S0
;TYPE:Perimeter
G1 E0.8
G2 X30 Y40 I0 J5 E1.5 F1200
M486 S-1
"""


@pytest.fixture
def prusa_file(tmp_path):
    path = tmp_path / "p.gcode"
    path.write_bytes(PRUSA_LIKE.encode())
    return str(path)


def test_index_by_comments(prusa_file):
    index = qa_gcode.build_index(prusa_file, "abc")
    assert index["source"] == "comments"
    assert index["numLayers"] == 2
    assert [layer["layer"] for layer in index["layers"]] == [1, 2]
    first, second = index["layers"]
    assert first["ranges"][0][1] == second["ranges"][0][0]
    assert second["ranges"][0][1] == os.path.getsize(prusa_file)
    assert second["state"]["x"] == 30 and second["state"]["rel_e"] is True
    assert index["objects"] == {"0": "cube"}


def test_layer_stats_with_slicer_retraction(prusa_file):
    first, second = qa_gcode.build_index(prusa_file, "abc")["layers"]
    assert first["stats"] == {"extrudeMm": 2.0, "types": {"External perimeter": 2.0}, "retracts": 1,
                              "fwRetracts": 0, "retractMm": 0.8, "macros": {}, "pathMm": 2.8, "macrosRetracted": {}}
    # the unretract is no printing move
    assert second["stats"]["extrudeMm"] == 1.5 and second["stats"]["retracts"] == 0


# OrcaSlicer with firmware retraction and the CHX 350's photo macro at each layer change, as in
# 3DBenchy_0.4_L0.18mm_N0.4_PLA_Meltingplot CHX 350_54m35s.gcode (2026-09-28)
FIRMWARE_RETRACTION = """M83
G10 P0 S220 R200
;LAYER_CHANGE
;Z:0.2
G10 ; retract
M98 P"0:/sys/meltingplot/timelapse/take-photo.g"
G1 X1 Y1 Z0.2 F60000
G11 ; unretract
;TYPE:Outer wall
G1 X10 Y1 E.5
G10 ; retract
G10
G1 X20 Y1 F60000
G11 ; unretract
;TYPE:Gap infill
G1 X20 Y10 E.3
;LAYER_CHANGE
;Z:0.4
G10 ; retract
M98 P"0:/sys/meltingplot/timelapse/take-photo.g"
G1 X1 Y1 Z0.4 F60000
G11 ; unretract
G1 X10 Y1 E.5
"""


def test_layer_stats_with_firmware_retraction(tmp_path):
    path = tmp_path / "orca.gcode"
    path.write_text(FIRMWARE_RETRACTION)
    first, second = qa_gcode.build_index(str(path))["layers"]
    # a G10 while retracted is the same retraction; G10 with P sets temperatures
    assert first["stats"] == {"extrudeMm": 0.8, "types": {"Outer wall": 0.5, "Gap infill": 0.3}, "retracts": 2,
                              "fwRetracts": 2, "retractMm": 0.0,
                              "macros": {"0:/sys/meltingplot/timelapse/take-photo.g": 1}, "pathMm": 0.8,
                              "macrosRetracted": {"0:/sys/meltingplot/timelapse/take-photo.g": 1}}
    assert second["stats"]["retracts"] == 1 and second["stats"]["types"] == {"Gap infill": 0.5}


# take-photo.g of the CHX 350 as it was on the machine on 2026-09-28 20:20 (2 mm back, 0.8 forward),
# shortened
TAKE_PHOTO = """if state.status == "simulating"
  M99
M400
G10                                               ; firmware retract (M207 of the loaded filament)
M83
G1 E-2 F1000
if var.x_parts < 0
  G53 G1 X{move.axes[0].max - 5} F60000
else
  G1 X{min(var.x_parts + var.clearance, move.axes[0].max - 5)} F60000
M240
G1 R3 Z0 F1200
G1 E0.8 F1200                                       ; the extra 2 mm back
G11
"""


def test_macro_stats(tmp_path):
    path = tmp_path / "take-photo.g"
    path.write_text(TAKE_PHOTO)
    stats = qa_gcode.macro_stats(str(path))
    assert {k: stats[k] for k in ("pathMm", "netMm", "fwRetracts", "approximate", "calls")} == {
        "pathMm": 2.8, "netMm": -1.2, "fwRetracts": 1, "approximate": False, "calls": []}
    assert len(stats["crc32"]) == 8
    path.write_text('M82\nG1 E5\nG1 E3\nG1 E{var.prime}\nM98 P"clean.g"\n')
    stats = qa_gcode.macro_stats(str(path))   # the first absolute E has no start, the expression no value
    assert (stats["pathMm"], stats["netMm"], stats["approximate"], stats["calls"]) == (2.0, -2.0, True, ["clean.g"])
    assert qa_gcode.macro_name("take-photo.g") == "0:/sys/take-photo.g"
    assert qa_gcode.macro_name("/macros/a.g") == "0:/macros/a.g"
    assert qa_gcode.macro_name("1:/sys/a.g") == "1:/sys/a.g"


def test_filament_path():
    stats = {"pathMm": 1.8, "retractMm": 0.4, "fwRetracts": 2, "macros": {"m.g": 2, "gone.g": 1},
             "macrosRetracted": {"m.g": 1}}
    macro = {"pathMm": 4.0, "netMm": 0.0, "fwRetracts": 1}
    result = qa_gcode.filament_path(stats, 800, {"length": 0.5, "extraRestart": 0.1}, {"m.g": macro})
    # file: 1.8 + 2 cycles of 1.1; macro twice 4 mm, one of its G10 counts (the other call was retracted)
    assert result["mm"] == pytest.approx(1.8 + 2.2 + 8 + 1.1)
    assert result["netMm"] == pytest.approx(1.0 + 0.2 + 0.1)
    assert result["gearPasses"] == pytest.approx(13.1 / 1.3, abs=0.01)
    assert result["motorSteps"] == round(13.1 * 800) and result["unknownMacros"] == ["gone.g"]
    # a macro that feeds back less than it retracts leaves no filament for the layer: no passes
    short = qa_gcode.filament_path({"pathMm": 0.5, "retractMm": 0, "fwRetracts": 0, "macros": {"m.g": 1}},
                                   None, None, {"m.g": {"pathMm": 2.8, "netMm": -1.2, "fwRetracts": 1}})
    assert short["gearPasses"] is None and short["netMm"] == pytest.approx(-0.7) and short["motorSteps"] is None


def test_toolpath_flow_and_objects(prusa_file):
    index = qa_gcode.build_index(prusa_file, "abc")
    tp = qa_gcode.toolpath(prusa_file, index, 1, filament_diameter=2.85)
    seg = tp["segments"]
    extruding = [i for i, travel in enumerate(seg["travel"]) if not travel]
    assert len(extruding) == 2
    i = extruding[0]
    assert (seg["x0"][i], seg["y0"][i], seg["x1"][i], seg["y1"][i]) == (10, 10, 20, 10)
    area = math.pi * (2.85 / 2) ** 2
    assert seg["flow"][i] == pytest.approx(1.0 * area / (10 / 20), rel=1e-3)
    assert seg["object"][i] == 0
    assert tp["types"][seg["type"][i]] == "External perimeter"
    assert seg["object"][-1] is None  # travel after M486 S-1


def test_toolpath_arc(prusa_file):
    index = qa_gcode.build_index(prusa_file, "abc")
    seg = qa_gcode.toolpath(prusa_file, index, 2, 2.85)["segments"]
    arc = [i for i, travel in enumerate(seg["travel"]) if not travel]
    assert len(arc) > 10  # a half circle of radius 5 in 1 mm chords
    assert (seg["x1"][arc[-1]], seg["y1"][arc[-1]]) == (30, 40)
    radius = [math.hypot(seg["x1"][i] - 30, seg["y1"][i] - 35) for i in arc]
    assert max(radius) == pytest.approx(5, abs=1e-3) and min(radius) == pytest.approx(5, abs=1e-3)
    assert sum(seg["e"][i] for i in arc) == pytest.approx(1.5, abs=1e-3)
    assert qa_gcode.toolpath(prusa_file, index, 9, 2.85) is None


def test_z_fallback_without_comments(tmp_path):
    path = tmp_path / "z.gcode"
    path.write_text("G90\nM82\nG92 E0\nG1 Z0.3\nG1 X10 Y0 E1\nG1 X20 Y0 E2\nG1 Z0.6\nG1 X10 Y0 E3\n"
                    "G1 Z5 F3000\nG1 X0 Y0\n")
    index = qa_gcode.build_index(str(path))
    assert index["source"] == "z"
    assert index["numLayers"] == 2
    assert [layer["stats"]["extrudeMm"] for layer in index["layers"]] == [2.0, 1.0]
    tp = qa_gcode.toolpath(str(path), index, 2)
    assert [e for e in tp["segments"]["e"] if e > 0] == [1.0]


@pytest.mark.skipif(not os.path.isdir(DSF_SAMPLES), reason="DuetSoftwareFramework checkout not next to this repo")
@pytest.mark.parametrize("name,layers", [("Cura.gcode", 418), ("Simplify3D.gcode", None)])
def test_real_slicer_files(name, layers):
    index = qa_gcode.build_index(os.path.join(DSF_SAMPLES, name))
    assert index["source"] == "comments"
    if layers is not None:
        assert index["numLayers"] == layers
    else:
        assert index["numLayers"] > 10


def test_index_cache(tmp_path, prusa_file):
    cache = qa_gcode.IndexCache(str(tmp_path))
    assert cache.get("abc") == (None, "missing")
    assert cache.ensure(prusa_file, "abc", run_async=False) == "ready"
    index, state = cache.get("abc")
    assert state == "ready" and index["numLayers"] == 2
    fresh = qa_gcode.IndexCache(str(tmp_path))  # from the JSON file
    assert fresh.get("abc")[1] == "ready"
    with open(os.path.join(str(tmp_path), "index", "old.json"), "w") as handle:
        json.dump({**index, "version": 1}, handle)
    assert fresh.get("old") == (None, "missing")  # an older version is built again
    assert cache.ensure("/nonexistent", "zzz", run_async=False).startswith("error")
